<<<<<<< HEAD
import { Inter } from "next/font/google"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "PAMS - Admin Dashboard",
  description: "Personnel Administration Management System",
=======
// app/layout.js
import './globals.css'

export const metadata = {
  title: 'My App',
  description: 'Generated by create next app',
>>>>>>> 58d541d (Made updates)
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body className={inter.className}>{children}</body>
=======
      <body>{children}</body>
>>>>>>> 58d541d (Made updates)
    </html>
  )
}
